# Data Acquisition

In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [15]:
base_URL = 'https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/?pagina='

In [16]:
# get ads in multiple pages and returns a list of dataFrames
def scrap(url, pages=2):
    '''Scraps search results from a real state website'''
    if pages < 2:
        raise ValueError('number of pages must be greater than 2')
    scrap_df = [] # list to hold all data frames created per page
    for p_no in range(1, pages):
        search_url = url + str(p_no)
        # check if request is successful
        try:
            page_content = requests.get(search_url).content
            print(search_url)
        except Exception as e:
            print(f'Failed to gather data from {search_url}')
            print(e)
    
        soup = BeautifulSoup(page_content) # get page content into soup

        rent_tag_list = soup.find_all('div', {'class': 'property-card__price js-property-card-prices js-property-card__price-small'}) # gets all rent tags
        rent_text_list = [rent.p.text for rent in rent_tag_list] # gets the text from each rent tag


        rooms_tag_list = soup.find_all('li', {'class': 'property-card__detail-item property-card__detail-room js-property-detail-rooms'})
        rooms_text_list = [room.span.text for room in rooms_tag_list]


        address_tag_list = soup.find_all('span', {'class': 'property-card__address'})
        address_text_list = [address.text for address in address_tag_list]


        bathroom_tag_list = soup.find_all('li', {'class': 'property-card__detail-item property-card__detail-bathroom js-property-detail-bathroom'})
        bathroom_text_list = [bathroom.span.text for bathroom in bathroom_tag_list]


        parking_tag_list = soup.find_all('li', {'class': 'property-card__detail-item property-card__detail-garage js-property-detail-garages'})
        parking_text_list = [parking.span.text for parking in parking_tag_list]

        area_tag_list = soup.find_all('span', {'class': 'property-card__detail-value js-property-card-value property-card__detail-area js-property-card-detail-area'})
        area_text_list = [area.text for area in area_tag_list]

        # create a dictionary to create a pandas dataframe
        data = {'address': address_text_list,
                'rent': rent_text_list,
                'rooms': rooms_text_list,
                'bathroom': bathroom_text_list,
                'parking': parking_text_list,
                'area': area_text_list}
        
        #create the dataFrame
        df = pd.DataFrame(data)
        print(df)
        scrap_df.append(df)
    
    final_data = pd.concat(scrap_df)
    # return final dataFrame
    return final_data

In [17]:
final_data = scrap(base_URL, 180)

, São Paul...    R$ 2.700 /Mês     1
9   Avenida Onze de Junho, 730 - Vila Clementino, ...    R$ 2.290 /Mês     2
10      Rua Helena, 52 - Vila Olímpia, São Paulo - SP    R$ 4.200 /Mês     2
11  Rua Marquês de Itu, 181 - Vila Buarque, São Pa...    R$ 2.500 /Mês     2
12  Rua Domingos da Costa Mata, 275 - Santana, São...    R$ 1.700 /Mês     3
13  Rua Henri Dunant, 1066 - Santo Amaro, São Paul...    R$ 2.880 /Mês     1
14  Rua Volta Redonda, 757 - Campo Belo, São Paulo...    R$ 7.000 /Mês     2
15  Rua Padre Carvalho, 68 - Pinheiros, São Paulo ...    R$ 2.950 /Mês     2
16  Rua Doutor Seng, 152 - Bela Vista, São Paulo - SP    R$ 1.500 /Mês     1
17  Rua Judith Zumkeller, 870 - Parque Mandaqui, S...    R$ 2.500 /Mês     2
18                 Vila Santo Estevão, São Paulo - SP    R$ 3.500 /Mês     4
19  Rua João Lourenço, 763 - Vila Nova Conceição, ...    R$ 5.500 /Mês     3
20  Rua Padre Bento Ibañez - Jardim Prudência, São...    R$ 1.300 /Mês     2
21  Rua Giovani Recordati, 153 - Parque São Doming...    R$ 3.100 /Mês     3
22  Rua Balthazar da Veiga, 539 - Vila Nova Concei...    R$ 4.000 /Mês     1
23  Rua São Vicente de Paulo, 401 - Santa Cecília,...    R$ 3.500 /Mês     2
24  Rua Manuel da Nóbrega, 646 - Paraíso, São Paul...    R$ 3.100 /Mês     1
25     Rua Araquém, 19 - Vila Mascote, São Paulo - SP    R$ 1.900 /Mês     2
26  Rua Cardoso de Almeida, 840 - Perdizes, São Pa...    R$ 2.250 /Mês     1
27         Rua Tucuna, 824 - Perdizes, São Paulo - SP    R$ 2.950 /Mês     1
28                               Lapa, São Paulo - SP    R$ 2.100 /Mês     2
29  Avenida Doutor Francisco Mesquita, 1139 - Quin...    R$ 1.600 /Mês     1
30  Avenida Paulista, 37 - Bela Vista, São Paulo - SP    R$ 3.350 /Mês     3
31  Rua Conselheiro Moreira de Barros, 884 - Santa...    R$ 3.000 /Mês     3
32  Rua Lisboa, 159 - Cerqueira César, São Paulo - SP    R$ 5.380 /Mês     2
33  Rua Pereira do Lago, 309 - Vila Gomes, São Pau...      R$ 990 /Mês     1
34      Alameda Itu - Jardim Paulista, São Paulo - SP    R$ 3.500 /Mês     3
35  Rua Pintassilgo, 480 - Vila Uberabinha, São Pa...    R$ 2.800 /Mês     1

   bathroom parking   area
0        2       1     80
1        1       1     47
2        1       1     30
3        2       1     37
4        1       1     45
5        1       1     45
6        1       1     30
7        1       1     57
8        1       1     33
9        2       1     53
10       2       1     60
11       1       1     50
12       2       1     62
13       1       1     33
14       5       3    276
15       2       1     60
16       1      --     36
17       1       1     60
18       2       4    145
19       2       1     80
20       1       1     45
21       2       2     74
22       1       1     40
23       2      --     90
24       2       2     50
25       3       1     84
26       1       1     36
27       1       1     50
28       2       1     58
29       1      --     50
30       2       1    116
31       4       3    156
32       2       1    163
33       1      --     20
34       2       1    115
35       2       1     70
https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/?pagina=176
                                              address               rent  \
0   Rua Celso Ramos, 145 - Vila Andrade, São Paulo...     R$ 1.950 /Mês
1   Praça da República, 401 - República, São Paulo...     R$ 2.300 /Mês
2   Rua Gomes de Carvalho, 1005 - Vila Olímpia, Sã...       R$ 800 /Mês
3   Rua da Consolação, 1515 - Consolação, São Paul...     R$ 2.700 /Mês
4       Rua Helena, 52 - Vila Olímpia, São Paulo - SP     R$ 4.200 /Mês
5   Rua Marquês de Itu, 181 - Vila Buarque, São Pa...     R$ 2.500 /Mês
6   Rua Domingos da Costa Mata, 275 - Santana, São...     R$ 1.700 /Mês
7   Rua Henri Dunant, 1066 - Santo Amaro, São Paul...     R$ 2.880 /Mês
8   Rua Volta Redonda, 757 - Campo Belo, São Paulo...     R$ 7.000 /Mês
9   Rua Padre Carvalho, 68 - Pinheiros, São Paulo ...     R$ 2.950 /Mês
10  Rua Doutor Seng, 152 - Bela Vista, São Paulo - SP     R$ 1.500 /Mês
11  Rua Judith Zumkeller, 870 - Parque Mandaqui, S...     R$ 2.500 /Mês
12  Rua João Lourenço, 763 - Vila Nova Conceição, ...     R$ 5.500 /Mês
13  Rua Padre Bento Ibañez - Jardim Prudência, São...     R$ 1.300 /Mês
14  Rua Giovani Recordati, 153 - Parque São Doming...     R$ 3.100 /Mês
15  Rua São Vicente de Paulo, 401 - Santa Cecília,...     R$ 3.500 /Mês
16     Rua Araquém, 19 - Vila Mascote, São Paulo - SP     R$ 1.900 /Mês
17                               Lapa, São Paulo - SP     R$ 2.100 /Mês
18  Rua Lisboa, 159 - Cerqueira César, São Paulo - SP     R$ 5.380 /Mês
19  Rua Pereira do Lago, 309 - Vila Gomes, São Pau...       R$ 990 /Mês
20      Alameda Itu - Jardim Paulista, São Paulo - SP     R$ 3.500 /Mês
21  Rua Pintassilgo, 480 - Vila Uberabinha, São Pa...     R$ 2.800 /Mês
22  Rua Camillo Nader, 175 - Vila Morumbi, São Pau...     R$ 2.500 /Mês
23  Rua Maria Antônia, 173 - Vila Buarque, São Pau...     R$ 1.500 /Mês
24  Rua Michael Faraday, 22 - Cidade Monções, São ...     R$ 1.700 /Mês
25  Rua Professor Pedro da Cunha, 28 - Perdizes, S...     R$ 1.400 /Mês
26  Rua Sílvio de Sousa - Vila Santa Clara, São Pa...     R$ 1.100 /Mês
27  Rua João Miguel Jarra, 298 - Vila Madalena, Sã...     R$ 1.900 /Mês
28  Rua Flórida, 1901 - Cidade Monções, São Paulo ...    R$ 12.000 /Mês
29        Rua Alvorada - Vila Olímpia, São Paulo - SP     R$ 3.146 /Mês
30  Rua Manuel da Nóbrega, 638 - Paraíso, São Paul...     R$ 3.500 /Mês
31  Rua Bacaetava, 66 - Vila Gertrudes, São Paulo ...     R$ 6.000 /Mês
32  Rua Verbo Divino, 1061 - Chácara Santo Antônio...     R$ 9.500 /Mês
33                          Pinheiros, São Paulo - SP     R$ 1.900 /Mês
34      Rua Guarani, 460 - Bom Retiro, São Paulo - SP     R$ 1.600 /Mês
35        Rua Baluarte - Vila Olímpia, São Paulo - SP     R$ 3.300 /Mês

   rooms bathroom parking   area
0     2        1       1     47
1     1        1       1     30
2     1        1       1     30
3     1        1       1     33
4     2        2       1     60
5     2        1       1     50
6     3        2       1     62
7     1        1       1     33
8     2        5       3    276
9     2        2       1     60
10    1        1      --     36
11    2        1       1     60
12    3        2       1     80
13    2        1       1     45
14    3        2       2     74
15    2        2      --     90
16    2        3       1     84
17    2        2       1     58
18    2        2       1    163
19    1        1      --     20
20    3        2       1    115
21    1        2       1     70
22    3        3       2    125
23    1        1      --     26
24    2        1       1     50
25    1        1      --     13
26    2        1       1     60
27    2        1       1     48
28    2        4       2    165
29    2        2       1     67
30    2        3       2     80
31    3        3       2     97
32    3        5       4    186
33    1        1      --     25
34    2        1      --     60
35    3        2       1     94
https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/?pagina=177
                                              address              rent rooms  \
0   Rua Oscar Freire, 1735 - Pinheiros, São Paulo ...    R$ 3.400 /Mês     2
1   Rua Celso Ramos, 145 - Vila Andrade, São Paulo...    R$ 1.950 /Mês     2
2   Praça da República, 401 - República, São Paulo...    R$ 2.300 /Mês     1
3    Rua dos Caciques - Vila da Saúde, São Paulo - SP    R$ 1.800 /Mês     1
4   Rua das Perobeiras - Chácara Santa Maria, São ...      R$ 900 /Mês     2
5   Rua Monte Aprazível, 109 - Vila Nova Conceição...    R$ 2.800 /Mês     1
6   Rua João Ferreira de Abreu - Vila Arriete, São...    R$ 1.400 /Mês     2
7   Rua Gomes de Carvalho, 1005 - Vila Olímpia, Sã...      R$ 800 /Mês     1
8     Rua Uruçuca, 34 - Vila Antonina, São Paulo - SP    R$ 2.000 /Mês     2
9   Rua Professor José Leite e Oiticica, 240 - Vil...    R$ 8.500 /Mês     3
10  Rua da Consolação, 1515 - Consolação, São Paul...    R$ 2.700 /Mês     1
11  Avenida Onze de Junho, 730 - Vila Clementino, ...    R$ 2.290 /Mês     2
12      Rua Helena, 52 - Vila Olímpia, São Paulo - SP    R$ 4.200 /Mês     2
13  Rua Marquês de Itu, 181 - Vila Buarque, São Pa...    R$ 2.500 /Mês     2
14  Rua Domingos da Costa Mata, 275 - Santana, São...    R$ 1.700 /Mês     3
15  Rua Henri Dunant, 1066 - Santo Amaro, São Paul...    R$ 2.880 /Mês     1
16  Rua Volta Redonda, 757 - Campo Belo, São Paulo...    R$ 7.000 /Mês     2
17  Rua Padre Carvalho, 68 - Pinheiros, São Paulo ...    R$ 2.950 /Mês     2
18  Rua Doutor Seng, 152 - Bela Vista, São Paulo - SP    R$ 1.500 /Mês     1
19  Rua Judith Zumkeller, 870 - Parque Mandaqui, S...    R$ 2.500 /Mês     2
20                 Vila Santo Estevão, São Paulo - SP    R$ 3.500 /Mês     4
21  Rua João Lourenço, 763 - Vila Nova Conceição, ...    R$ 5.500 /Mês     3
22  Rua Padre Bento Ibañez - Jardim Prudência, São...    R$ 1.300 /Mês     2
23  Rua Giovani Recordati, 153 - Parque São Doming...    R$ 3.100 /Mês     3
24  Rua Balthazar da Veiga, 539 - Vila Nova Concei...    R$ 4.000 /Mês     1
25  Rua São Vicente de Paulo, 401 - Santa Cecília,...    R$ 3.500 /Mês     2
26  Rua Manuel da Nóbrega, 646 - Paraíso, São Paul...    R$ 3.100 /Mês     1
27     Rua Araquém, 19 - Vila Mascote, São Paulo - SP    R$ 1.900 /Mês     2
28  Rua Cardoso de Almeida, 840 - Perdizes, São Pa...    R$ 2.250 /Mês     1
29         Rua Tucuna, 824 - Perdizes, São Paulo - SP    R$ 2.950 /Mês     1
30                               Lapa, São Paulo - SP    R$ 2.100 /Mês     2
31  Avenida Doutor Francisco Mesquita, 1139 - Quin...    R$ 1.600 /Mês     1
32  Avenida Paulista, 37 - Bela Vista, São Paulo - SP    R$ 3.350 /Mês     3
33  Rua Conselheiro Moreira de Barros, 884 - Santa...    R$ 3.000 /Mês     3
34  Rua Lisboa, 159 - Cerqueira César, São Paulo - SP    R$ 5.380 /Mês     2
35  Rua Pereira do Lago, 309 - Vila Gomes, São Pau...      R$ 990 /Mês     1

   bathroom parking   area
0        2       1     80
1        1       1     47
2        1       1     30
3        2       1     37
4        1       1     45
5        1       1     32
6        1       1     45
7        1       1     30
8        1       1     57
9        5       2    150
10       1       1     33
11       2       1     53
12       2       1     60
13       1       1     50
14       2       1     62
15       1       1     33
16       5       3    276
17       2       1     60
18       1      --     36
19       1       1     60
20       2       4    145
21       2       1     80
22       1       1     45
23       2       2     74
24       1       1     40
25       2      --     90
26       2       2     50
27       3       1     84
28       1       1     36
29       1       1     50
30       2       1     58
31       1      --     50
32       2       1    116
33       4       3    156
34       2       1    163
35       1      --     20
https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/?pagina=178
                                              address               rent  \
0   Rua Oscar Freire, 1735 - Pinheiros, São Paulo ...     R$ 3.400 /Mês
1   Rua Celso Ramos, 145 - Vila Andrade, São Paulo...     R$ 1.950 /Mês
2   Praça da República, 401 - República, São Paulo...     R$ 2.300 /Mês
3    Rua dos Caciques - Vila da Saúde, São Paulo - SP     R$ 1.800 /Mês
4   Rua das Perobeiras - Chácara Santa Maria, São ...       R$ 900 /Mês
5   Rua João Ferreira de Abreu - Vila Arriete, São...     R$ 1.400 /Mês
6   Rua Gomes de Carvalho, 1005 - Vila Olímpia, Sã...       R$ 800 /Mês
7     Rua Uruçuca, 34 - Vila Antonina, São Paulo - SP     R$ 2.000 /Mês
8   Rua da Consolação, 1515 - Consolação, São Paul...     R$ 2.700 /Mês
9   Avenida Onze de Junho, 730 - Vila Clementino, ...     R$ 2.290 /Mês
10      Rua Helena, 52 - Vila Olímpia, São Paulo - SP     R$ 4.200 /Mês
11  Rua Marquês de Itu, 181 - Vila Buarque, São Pa...     R$ 2.500 /Mês
12  Rua Domingos da Costa Mata, 275 - Santana, São...     R$ 1.700 /Mês
13  Rua Henri Dunant, 1066 - Santo Amaro, São Paul...     R$ 2.880 /Mês
14  Rua Volta Redonda, 757 - Campo Belo, São Paulo...     R$ 7.000 /Mês
15  Rua Doutor Seng, 152 - Bela Vista, São Paulo - SP     R$ 1.500 /Mês
16  Rua Judith Zumkeller, 870 - Parque Mandaqui, S...     R$ 2.500 /Mês
17                 Vila Santo Estevão, São Paulo - SP     R$ 3.500 /Mês
18  Rua João Lourenço, 763 - Vila Nova Conceição, ...     R$ 5.500 /Mês
19  Rua Padre Bento Ibañez - Jardim Prudência, São...     R$ 1.300 /Mês
20  Rua Giovani Recordati, 153 - Parque São Doming...     R$ 3.100 /Mês
21  Rua Balthazar da Veiga, 539 - Vila Nova Concei...     R$ 4.000 /Mês
22  Rua São Vicente de Paulo, 401 - Santa Cecília,...     R$ 3.500 /Mês
23  Rua Manuel da Nóbrega, 646 - Paraíso, São Paul...     R$ 3.100 /Mês
24     Rua Araquém, 19 - Vila Mascote, São Paulo - SP     R$ 1.900 /Mês
25  Rua Cardoso de Almeida, 840 - Perdizes, São Pa...     R$ 2.250 /Mês
26         Rua Tucuna, 824 - Perdizes, São Paulo - SP     R$ 2.950 /Mês
27  Avenida Doutor Francisco Mesquita, 1139 - Quin...     R$ 1.600 /Mês
28  Avenida Paulista, 37 - Bela Vista, São Paulo - SP     R$ 3.350 /Mês
29  Rua Conselheiro Moreira de Barros, 884 - Santa...     R$ 3.000 /Mês
30  Rua Lisboa, 159 - Cerqueira César, São Paulo - SP     R$ 5.380 /Mês
31  Rua Pereira do Lago, 309 - Vila Gomes, São Pau...       R$ 990 /Mês
32      Alameda Itu - Jardim Paulista, São Paulo - SP     R$ 3.500 /Mês
33  Rua Pintassilgo, 480 - Vila Uberabinha, São Pa...     R$ 2.800 /Mês
34  Rua Camillo Nader, 175 - Vila Morumbi, São Pau...     R$ 2.500 /Mês
35  Rua José Antônio Coelho - Vila Mariana, São Pa...    R$ 11.800 /Mês

   rooms bathroom parking   area
0     2        2       1     80
1     2        1       1     47
2     1        1       1     30
3     1        2       1     37
4     2        1       1     45
5     2        1       1     45
6     1        1       1     30
7     2        1       1     57
8     1        1       1     33
9     2        2       1     53
10    2        2       1     60
11    2        1       1     50
12    3        2       1     62
13    1        1       1     33
14    2        5       3    276
15    1        1      --     36
16    2        1       1     60
17    4        2       4    145
18    3        2       1     80
19    2        1       1     45
20    3        2       2     74
21    1        1       1     40
22    2        2      --     90
23    1        2       2     50
24    2        3       1     84
25    1        1       1     36
26    1        1       1     50
27    1        1      --     50
28    3        2       1    116
29    3        4       3    156
30    2        2       1    163
31    1        1      --     20
32    3        2       1    115
33    1        2       1     70
34    3        3       2    125
35    2        3       3    134
https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/?pagina=179
                                              address              rent rooms  \
0   Rua Oscar Freire, 1735 - Pinheiros, São Paulo ...    R$ 3.400 /Mês     2
1       Rua Helena, 52 - Vila Olímpia, São Paulo - SP    R$ 4.200 /Mês     2
2   Rua Gomes de Carvalho, 1005 - Vila Olímpia, Sã...      R$ 800 /Mês     1
3    Rua dos Caciques - Vila da Saúde, São Paulo - SP    R$ 1.800 /Mês     1
4   Rua das Perobeiras - Chácara Santa Maria, São ...      R$ 900 /Mês     2
5   Rua Monte Aprazível, 109 - Vila Nova Conceição...    R$ 2.800 /Mês     1
6   Rua João Ferreira de Abreu - Vila Arriete, São...    R$ 1.400 /Mês     2
7   Rua Celso Ramos, 145 - Vila Andrade, São Paulo...    R$ 1.950 /Mês     2
8     Rua Uruçuca, 34 - Vila Antonina, São Paulo - SP    R$ 2.000 /Mês     2
9   Rua Professor José Leite e Oiticica, 240 - Vil...    R$ 8.500 /Mês     3
10  Rua João Lourenço, 763 - Vila Nova Conceição, ...    R$ 5.500 /Mês     3
11  Avenida Onze de Junho, 730 - Vila Clementino, ...    R$ 2.290 /Mês     2
12  Rua Domingos da Costa Mata, 275 - Santana, São...    R$ 1.700 /Mês     3
13  Rua Henri Dunant, 1066 - Santo Amaro, São Paul...    R$ 2.880 /Mês     1
14  Rua Henri Dunant, 792 - Santo Amaro, São Paulo...    R$ 5.500 /Mês     2
15  Rua Raul Pompéia, 745 - Vila Pompéia, São Paul...    R$ 2.000 /Mês     2
16  Rua Judith Zumkeller, 870 - Parque Mandaqui, S...    R$ 2.500 /Mês     2
17                 Vila Santo Estevão, São Paulo - SP    R$ 3.500 /Mês     4
18  Rua Sansão Alves dos Santos, 343 - Cidade Monç...    R$ 6.100 /Mês     2
19  Rua Padre Bento Ibañez - Jardim Prudência, São...    R$ 1.300 /Mês     2
20  Rua Gonçalo da Cunha - Chácara Inglesa, São Pa...    R$ 3.300 /Mês     2
21  Rua Estado de Rondônia, 114 - Jardim Cidade Pi...    R$ 1.700 /Mês     2
22  Rua Giovani Recordati, 153 - Parque São Doming...    R$ 3.100 /Mês     3
23  Rua Balthazar da Veiga, 539 - Vila Nova Concei...    R$ 4.000 /Mês     1
24  Rua São Vicente de Paulo, 401 - Santa Cecília,...    R$ 3.500 /Mês     2
25  Rua Manuel da Nóbrega, 646 - Paraíso, São Paul...    R$ 3.100 /Mês     1
26  Rua Cardoso de Almeida, 840 - Perdizes, São Pa...    R$ 2.250 /Mês     1
27         Rua Tucuna, 824 - Perdizes, São Paulo - SP    R$ 2.950 /Mês     1
28  Rua da Consolação, 1515 - Consolação, São Paul...    R$ 2.700 /Mês     1
29  Avenida Doutor Francisco Mesquita, 1139 - Quin...    R$ 1.600 /Mês     1
30  Rua Teodoro Sampaio, 498 - Pinheiros, São Paul...    R$ 3.000 /Mês     2
31  Avenida Paulista, 37 - Bela Vista, São Paulo - SP    R$ 3.350 /Mês     3
32  Rua Conselheiro Moreira de Barros, 884 - Santa...    R$ 3.000 /Mês     3
33  Rua Lisboa, 159 - Cerqueira César, São Paulo - SP    R$ 5.380 /Mês     2
34  Rua Pereira do Lago, 309 - Vila Gomes, São Pau...      R$ 990 /Mês     1
35  Alameda dos Arapanés, 628 - Moema, São Paulo - SP    R$ 8.000 /Mês     3

   bathroom parking   area
0        2       1     80
1        2       1     60
2        1       1     30
3        2       1     37
4        1       1     45
5        1       1     32
6        1       1     45
7        1       1     47
8        1       1     57
9        5       2    150
10       2       1     80
11       2       1     53
12       2       1     62
13       1       1     33
14       3       2     78
15       2       1     81
16       1       1     60
17       2       4    145
18       2       2     75
19       1       1     45
20       2       1     68
21       1      --     40
22       2       2     74
23       1       1     40
24       2      --     90
25       2       2     50
26       1       1     36
27       1       1     50
28       1       1     33
29       1      --     50
30       1       1     75
31       2       1    116
32       4       3    156
33       2       1    163
34       1      --     20
35       5       3    198

In [18]:
final_data.head(72)

,address,rent,rooms,bathroom,parking,area
0,"Rua Oscar Freire, 1735 - Pinheiros, São Paulo ...",R$ 3.400 /Mês,2,2,1,80
1,"Rua Celso Ramos, 145 - Vila Andrade, São Paulo...",R$ 1.950 /Mês,2,1,1,47
2,"Praça da República, 401 - República, São Paulo...",R$ 2.300 /Mês,1,1,1,30
3,"Rua dos Caciques - Vila da Saúde, São Paulo - SP",R$ 1.800 /Mês,1,2,1,37
4,"Rua das Perobeiras - Chácara Santa Maria, São ...",R$ 900 /Mês,2,1,1,45
...,...,...,...,...,...,...
31,"Rua Bacaetava, 66 - Vila Gertrudes, São Paulo ...",R$ 6.000 /Mês,3,3,2,97
32,"Rua Verbo Divino, 1061 - Chácara Santo Antônio...",R$ 9.500 /Mês,3,5,4,186
33,"Pinheiros, São Paulo - SP",R$ 1.900 /Mês,1,1,--,25
34,"Rua Guarani, 460 - Bom Retiro, São Paulo - SP",R$ 1.600 /Mês,2,1,--,60
35,"Rua Baluarte - Vila Olímpia, São Paulo - SP",R$ 3.300 /Mês,3,2,1,94

In [19]:
final_data['suburb'] = final_data.address.str.split('\s-').str[1].str.split(', ').str[0]

In [20]:
final_data

,address,rent,rooms,bathroom,parking,area,suburb
0,"Rua Oscar Freire, 1735 - Pinheiros, São Paulo ...",R$ 3.400 /Mês,2,2,1,80,Pinheiros
1,"Rua Celso Ramos, 145 - Vila Andrade, São Paulo...",R$ 1.950 /Mês,2,1,1,47,Vila Andrade
2,"Praça da República, 401 - República, São Paulo...",R$ 2.300 /Mês,1,1,1,30,República
3,"Rua dos Caciques - Vila da Saúde, São Paulo - SP",R$ 1.800 /Mês,1,2,1,37,Vila da Saúde
4,"Rua das Perobeiras - Chácara Santa Maria, São ...",R$ 900 /Mês,2,1,1,45,Chácara Santa Maria
...,...,...,...,...,...,...,...
31,"Avenida Paulista, 37 - Bela Vista, São Paulo - SP",R$ 3.350 /Mês,3,2,1,116,Bela Vista
32,"Rua Conselheiro Moreira de Barros, 884 - Santa...",R$ 3.000 /Mês,3,4,3,156,Santana
33,"Rua Lisboa, 159 - Cerqueira César, São Paulo - SP",R$ 5.380 /Mês,2,2,1,163,Cerqueira César
34,"Rua Pereira do Lago, 309 - Vila Gomes, São Pau...",R$ 990 /Mês,1,1,--,20,Vila Gomes
35,"Alameda dos Arapanés, 628 - Moema, São Paulo - SP",R$ 8.000 /Mês,3,5,3,198,Moema

In [21]:
pd.DataFrame.nunique(final_data)

address     82
rent        52
rooms        4
bathroom     6
parking      6
area        57
suburb      48
dtype: int64

In [22]:
pd.DataFrame.drop_duplicates(final_data)

,address,rent,rooms,bathroom,parking,area,suburb
0,"Rua Oscar Freire, 1735 - Pinheiros, São Paulo ...",R$ 3.400 /Mês,2,2,1,80,Pinheiros
1,"Rua Celso Ramos, 145 - Vila Andrade, São Paulo...",R$ 1.950 /Mês,2,1,1,47,Vila Andrade
2,"Praça da República, 401 - República, São Paulo...",R$ 2.300 /Mês,1,1,1,30,República
3,"Rua dos Caciques - Vila da Saúde, São Paulo - SP",R$ 1.800 /Mês,1,2,1,37,Vila da Saúde
4,"Rua das Perobeiras - Chácara Santa Maria, São ...",R$ 900 /Mês,2,1,1,45,Chácara Santa Maria
...,...,...,...,...,...,...,...
31,"Estrada de Itapecerica, 1528 - Vila Prel, São ...",R$ 1.900 /Mês,2,1,1,48,Vila Prel
32,"Rua Peixoto Gomide - Jardim Paulista, São Paul...",R$ 3.900 /Mês,2,1,1,52,Jardim Paulista
33,"Rua Vupabussu - Pinheiros, São Paulo - SP",R$ 3.200 /Mês,2,1,1,56,Pinheiros
34,"Rua Plínio Salgado, 245 - Jardim Peri Peri, Sã...",R$ 850 /Mês,1,1,--,15,Jardim Peri Peri
35,"Rua Balthazar da Veiga - Vila Nova Conceição, ...",R$ 1.800 /Mês,1,1,1,36,Vila Nova Conceição